[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true

[program:laravel-queue]
command=php /var/www/html/artisan queue:work rabbitmq --sleep=3 --tries=3
autostart=true
autorestart=true
