<?php

declare(strict_types=1);

namespace Modules\Barcode\Infrastructure\Printing\Drivers;

use Modules\Barcode\Domain\Entities\BarcodeDefinition;
use Modules\Barcode\Domain\Entities\LabelTemplate;
use Modules\Barcode\Domain\ValueObjects\BarcodeOutputFormat;
use Modules\Barcode\Infrastructure\Generators\BarcodeGeneratorDispatcher;
use Modules\Barcode\Infrastructure\Printing\BarcodePrinterDriverInterface;

/**
 * Renders label output as a self-contained SVG document.
 *
 * This driver wraps the barcode SVG generated by BarcodeGeneratorDispatcher
 * inside a larger SVG label canvas that also includes the human-readable text,
 * optional title, and configurable dimensions. It is suitable for web display,
 * PDF conversion, and inkjet/laser printing.
 *
 * When a LabelTemplate is provided its {{ barcode_svg }} placeholder is
 * replaced with the generated barcode SVG before other substitutions are
 * applied.
 */
class SvgLabelDriver implements BarcodePrinterDriverInterface
{
    public function __construct(
        private readonly BarcodeGeneratorDispatcher $generator,
    ) {}

    public function getFormat(): string
    {
        return 'svg';
    }

    public function render(
        BarcodeDefinition $definition,
        ?LabelTemplate    $template,
        array             $variables,
    ): string {
        $barcodeSvg = $this->generator->generate($definition, BarcodeOutputFormat::SVG, []);

        $variables = $this->buildVariables($definition, $barcodeSvg, $variables);

        if ($template !== null) {
            return $template->render($variables);
        }

        return $this->buildDefaultSvgLabel($definition, $barcodeSvg, $variables);
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    /** @return array<string,string> */
    private function buildVariables(BarcodeDefinition $def, string $barcodeSvg, array $extra): array
    {
        return array_merge([
            'barcode_value' => $def->getValue(),
            'barcode_label' => $def->getLabel() ?? $def->getValue(),
            'barcode_type'  => $def->getType(),
            'barcode_svg'   => $barcodeSvg,
        ], $extra);
    }

    private function buildDefaultSvgLabel(
        BarcodeDefinition $def,
        string            $barcodeSvg,
        array             $vars,
    ): string {
        $label      = htmlspecialchars($vars['barcode_label'], ENT_XML1);
        $labelWidth = 300;
        $labelHeight = 160;

        // Strip outer <svg> wrapper from barcode SVG so we can embed it
        $innerSvg = preg_replace('/<\?xml[^>]*\?>/', '', $barcodeSvg);
        $innerSvg = preg_replace('/<svg[^>]*>/', '<svg x="10" y="10" width="280" height="100">', $innerSvg, 1);

        return sprintf(
            '<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d">' .
            '<rect width="%d" height="%d" fill="white" stroke="#ccc" stroke-width="1"/>' .
            '%s' .
            '<text x="%d" y="%d" font-family="monospace" font-size="12" text-anchor="middle" fill="black">%s</text>' .
            '</svg>',
            $labelWidth, $labelHeight,
            $labelWidth, $labelHeight,
            $labelWidth, $labelHeight,
            $innerSvg,
            (int) ($labelWidth / 2),
            $labelHeight - 10,
            $label,
        );
    }
}
