# RabbitMQ Configuration for IMS
loopback_users.guest = false
listeners.tcp.default = 5672
management.listener.port = 15672
definitions.import_backend = local_filesystem
definitions.local.path = /etc/rabbitmq/definitions.json
